## Betting Odds Selector

In [1]:
import sys
path_to_working_script = r'C:\Users\greg\Documents\NFL\bettors_probs\bettors_probs'
sys.path.append(path_to_working_script)

import bettors_probs
import pandas as pd
import pickle
import warnings
import matplotlib.pyplot as plt
plt.style.use('seaborn-white')

In [9]:
# load the starting dataframe
path = r'C:\Users\greg\Documents\NFL\bettors_probs\source_data'
file = 'week_7.xlsx'
week7 = pd.read_excel(path+'\\'+file)
file = 'week_10.xlsx'
week10 = pd.read_excel(path+'\\'+file)

# load the regression model pickle file
file = 'log_reg_spread_model.pkl'
loaded_model = pickle.load(open(path+'\\'+file, 'rb'))

In [3]:
week7

Rank                  Team  Bettors  Spread
0     1         Buffalo Bills     0.65   -17.0
1     2   San Francisco 49ers     0.24    -9.5
2     3     Green Bay Packers     0.04    -5.5
3     4  New England Patriots     0.02    -9.5
4     5  Jacksonville Jaguars     0.01    -3.5
5     6    Kansas City Chiefs     0.01    -3.0
6     7      Los Angeles Rams     0.01    -3.0
7     8       New York Giants     0.01    -3.0

In [4]:
# create a BettorsProbs object
bp = bettors_probs.BettorsProbs()

In [5]:
# return some prbabilities from spreads
probs = bp.probs_spreads(spreads = week7.Spread, model = loaded_model)

In [6]:
week7['Probs'] = probs
week7

Rank                  Team  Bettors  Spread     Probs
0     1         Buffalo Bills     0.65   -17.0  0.920713
1     2   San Francisco 49ers     0.24    -9.5  0.789509
2     3     Green Bay Packers     0.04    -5.5  0.672440
3     4  New England Patriots     0.02    -9.5  0.789509
4     5  Jacksonville Jaguars     0.01    -3.5  0.602976
5     6    Kansas City Chiefs     0.01    -3.0  0.584807
6     7      Los Angeles Rams     0.01    -3.0  0.584807
7     8       New York Giants     0.01    -3.0  0.584807

In [7]:
bp.bet_strength(bettors  = week7.Bettors,
                       probs = week7.Probs)

C:\Users\greg\Documents\NFL\bettors_probs\bettors_probs\bettors_probs.py:77: RuntimeWarning: invalid value encountered in true_divide
  cond_prob = np.where(rem_bet>0, 1, 0)/rem_bet.sum(axis = 1)[:, np.newaxis]


array([1.0211626 , 0.95653829, 0.95122945, 1.17135512, 0.90096199,
       0.87297393, 0.87297393, 0.87297393])

In [8]:
bp.bet_strength(bettors  = week7.Bettors,
                       spreads = week7.Spread, model = loaded_model)

C:\Users\greg\Documents\NFL\bettors_probs\bettors_probs\bettors_probs.py:77: RuntimeWarning: invalid value encountered in true_divide
  cond_prob = np.where(rem_bet>0, 1, 0)/rem_bet.sum(axis = 1)[:, np.newaxis]


array([1.0211626 , 0.95653829, 0.95122945, 1.17135512, 0.90096199,
       0.87297393, 0.87297393, 0.87297393])

In [10]:
bp.bet_strength(bettors  = week10.Bettors,
                       spreads = week10.Spread, model = loaded_model)

C:\Users\greg\Documents\NFL\bettors_probs\bettors_probs\bettors_probs.py:77: RuntimeWarning: invalid value encountered in true_divide
  cond_prob = np.where(rem_bet>0, 1, 0)/rem_bet.sum(axis = 1)[:, np.newaxis]


array([0.91519532, 1.08458788, 1.23551592, 1.0409701 , 0.91273695,
       0.97329465, 1.03223312, 0.94317997, 0.97329465, 0.91273695])